name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
        
    - name: Run build
      uses: borales/actions-yarn@v4
      with:
        cmd: build # will run `yarn build` command

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: deploy # will run `yarn deploy` command
